export const SITE_CONFIG = {
  name: 'SUSHI MIST',
  description: '“Más que sushi, una experiencia.”',
  whatsappNumber: '5352473962',
  currency: '$',
  deliveryArea: 'Envíos a domicilio en toda la ciudad.',
  openingHours: {
    start: 11,
    end: 20,
    display: 'Lunes - Domingo: 11:00 AM - 8:00 PM',
  },
  siteUrl: 'https://sushimist.com', // IMPORTANT: Change this to your live site URL
  defaultMetaDescription: 'Más que sushi, una experiencia. Los mejores rolls y platos orientales.',
  defaultOgImage: '../public/favicon.png', // Path to a default social sharing image
};

export const MENU = [
  // SUSHI
  {
  id: 'imperio-samurai',
  name: 'Imperio Samurai',
  description: 'Sushi con extra de atún rojo. Interior de alga nori, atún rojo con cebolla y pimiento; exterior de arroz con más atún rojo, salsa de pepino y mayonesa',
  price: 2500,
  category: 'Sushi',
  img: 'kumo-roll.png',
  availability: false,
},
  {
  id: 'Akai Maki ',
  name: 'Akai Maki ',
  description: 'Roll relleno de surimi suave y jugoso, combinado con un toque de vegetales frescos. Por fuera, arroz perfectamente sazonado cubierto con delicadas láminas de surimi y ajonjolí tostado, creando una mezcla irresistible de texturas y sabor',
  price: 2500,
  category: 'Sushi',
  img: 'IMG_9542.jpeg',
  availability: true,
},
{
  id: 'wakame-sumo-bowl',
  name: 'Wakame Sumo Bowl',
  description: 'Empanadas de curry y carne prensada acompañadas de arroz, vegetales marinados y alga kombu',
  price: 1700,
  category: 'Bowl',
  img: 'IMG_9543.jpeg',
  availability: true,
},
{
  id: 'arroz-frito',
  name: 'Arroz Frito',
  description: 'Arroz salteado con vegetales, salsa de soja, condimentos japoneses, aceite de sésamo, tortilla, wakame y carne',
  price: 2450,
  category: 'Calientes',
  img: 'IMG_9548.jpeg',
  availability: true,
},
{
  id: 'gunkan-su',
  name: 'Gunkan Su',
  description: 'Base de arroz con relleno de surimi en cubos y vegetales salteados',
  price: 1950,
  category: 'Sushi',
  img: 'IMG_9549.jpeg',
  availability: true,
},
{
  id: 'surimist',
  name: 'Surimist',
  description: 'Sushi relleno de surimi con vegetales salteados',
  price: 2000,
  category: 'Sushi',
  img: 'IMG_9530.jpeg',
  availability: true,
},
{
  id: 'ramen-carne',
  name: 'Ramen de Carne',
  description: 'Fideos Wai Wai en caldo de wakame con brotes de soja, soja tradicional, cebolleta, carne agridulce mechada y huevo hervido',
  price: 2300,
  category: 'Ramen',
  img: 'IMG_9546.jpeg',
  availability: true,
},
{
  id: 'ramen-surimi',
  name: 'Ramen de Surimi',
  description: 'Fideos Wai Wai en caldo de wakame con brotes de soja, soja tradicional, cebolleta, surimi estofado y huevo hervido',
  price: 2200,
  category: 'Ramen',
  img: 'IMG_9547.jpeg',
  availability: true,
},
{
  id: 'nigiri-surimi',
  name: 'Nigiri de Surimi',
  description: 'Base de arroz con láminas de surimi a la plancha y salsa especial de cebolla con miel',
  price: 1950,
  category: 'Sushi',
  img: 'IMG_9561.jpeg',
  availability: true,
},

// ENTRANTES
{
  id: 'tartar-surimi',
  name: 'Tartar de Surimi y Verduras',
  description: 'Delicado tartar de surimi fresco con vegetales finamente cortados, salteados en aceite de oliva, con un toque cítrico y especias que realzan su sabor',
  price: 1200,
  category: 'Entrantes',
  img: 'IMG_9556.jpeg',
  availability: true,
},
{
  id: 'empanadas-samosa',
  name: 'Empanadas Samosa',
  description: 'Empanadas crujientes rellenas de curry y carne prensada con masa extra fina',
  price: 950,
  category: 'Entrantes',
  img: 'IMG_9555.jpeg',
  availability: true,
},

// POSTRES
{
  id: 'flan-caramelo',
  name: 'Flan de Caramelo',
  description: 'Suave flan casero bañado en caramelo dulce',
  price: 400,
  category: 'Postres',
  img: 'IMG_9526.jpeg',
  availability: true,
},
  {
    id: 'kumo-roll',
    name: 'Kumo Roll (Rollo nube)',
    description: 'Relleno de queso, mayonesa y cebolla (opción caramelizada).',
    price: 1700,
    category: 'Sushi',
    img: 'IMG_9544.jpeg',
    availability: true,
  },
  {
    id: 'midori-roll',
    name: 'Midori Roll (Rollo Verde)',
    description: 'Con aguacate, ají, cebollino y pepino en vinagreta. (Fresco y saludable.)',
    price: 1850,
    category: 'Sushi',
    img: '9b576480-20d3-4f33-96ce-c685fc3c2958.jpeg',
    availability: true,
  },
  {
    id: 'mist-blue',
    name: 'Mist Blue',
    description: '(Atún rojo de cola azul) a la plancha con cebolla, pimienta y ajo.',
    price: 1950,
    category: 'Sushi',
    img: 'mist-blue.png',
    availability: false,
  },
  {
    id: 'samurai-roll',
    name: 'Samurái Roll',
    description: '(Atún rojo de cola azul) Salteado en fajitas con salsa de soja y especias especiales japonesas.',
    price: 2250,
    category: 'Sushi',
    img: 'samurai-roll.jpg',
    availability: false,
  },
  {
    id: 'perla-roja',
    name: 'Perla Roja',
    description: '(Atún rojo de cola azul) semicrudo aliñado en vinagre especial.',
    price: 1900,
    category: 'Sushi',
    img: 'perla-roja.png',
    availability: false,
  },
  {
    id: 'sakura-beef-roll',
    name: 'Sakura Beef Roll',
    description: '(SUSHI de Carne) Carne jugosa con aguacate fresco, envuelto en alga nori y arroz japonés.',
    price: 2200,
    category: 'Sushi',
    img: '6811a695-d520-49df-a17b-59110aaab10d.jpeg',
    availability: true,
  },
  
  // OTROS PLATOS
  {
    id: 'bushi-green-noodles',
    name: 'Bushi Green Noodles',
    description: '(Fideos verdes de té MATCHA) con pasta de queso, coronados con cebolla y ají caramelizado.',
    price: 1850,
    category: 'Otros Platos',
    img: 'IMG_9553.jpeg',
    availability: true,
  },
  {
    id: 'temaki-camarones',
    name: 'TEMAKI de Camarones',
    description: 'Conos de alga rellenos de camarones frescos, directo a tu mesa. Delicia Japonesa.',
    price: 2050,
    category: 'Otros Platos',
    img: 'temaki.jpg',
    availability: false,
  },
  {
    id: 'onigiri-japones',
    name: 'ONIGIRI japonés',
    description: 'Deliciosos triángulos de arroz rellenos de carne mechada, listos para llevarte a Japón en cada mordida. Incluye 5 unidades.',
    price: 2000,
    category: 'Otros Platos',
    img: 'IMG_9525.jpeg',
    availability: true,
  },
  {
    id: 'ebi-camarones',
    name: 'Ebi de Camarones',
    description: 'Camarones al ajillo, delicadamente adobados para lograr un sabor irresistible y textura perfecta.',
    price: 2000,
    category: 'Otros Platos',
    img: 'ebi-camarones.png',
    availability: false,
  },

  // BEBIDAS
  {
    id: 'refrescos',
    name: 'Refrescos',
    description: 'Refrescos de diferente sabor.',
    price: 450,
    category: 'Bebidas',
    img: 'IMG_9577.jpeg',
    availability: true,
  },
  {
    id: 'cerveza-fria',
    name: 'Cerveza fría',
    description: 'Cerveza bien fría para acompañar tu sushi.',
    price: 0,
    category: 'Bebidas',
    img: 'cerveza.png',
    availability: false,
  },

  // SALSAS
  {
    id: 'salsas-variadas',
    name: 'Salsas Japonesas',
    description: 'Wasabi, Soja tradicional, Spaicy Sweet Soy, Hoisin Sauce, Soja Agridulce, Soja oscura, paquetes de soja sauce',
    price: 0,
    category: 'Salsas',
    img: 'IMG_9564.jpeg',
    availability: true,
  },
];
